- hosts: all
  become: yes
  become_user: root
  become_method: su
  tasks:
  - name: install apache
    yum:
      update_cache=yes
      state=inst_answer
      name={{item}}
    with_items: 
    - httpd
